/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import javax.swing.JOptionPane;

/**
 *
 * @author frank
 */
public class Inicio extends javax.swing.JFrame {
    private Juego game;
    private boolean metBusqueda;
    /**
     * Creates new form Inicio
   
     */
    public Inicio() {
        initComponents();
        this.metBusqueda=true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonInicio = new javax.swing.JButton();
        cargarPartida = new javax.swing.JButton();
        numColumnas = new javax.swing.JTextField();
        numFilas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numBombs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        busqueda = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("BUSCAMINAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 30, -1, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Franco Barra ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        botonInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonInicio.setText("Iniciar");
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });
        jPanel1.add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        cargarPartida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cargarPartida.setText("Cargar Partida");
        cargarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarPartidaActionPerformed(evt);
            }
        });
        jPanel1.add(cargarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        numColumnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numColumnasActionPerformed(evt);
            }
        });
        jPanel1.add(numColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 140, 50));
        jPanel1.add(numFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 140, 50));

        jLabel3.setText("Ingrese el número de columnas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel4.setText("Ingrese el numero de filas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));
        jPanel1.add(numBombs, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 160, 50));

        jLabel5.setText("Ingrese el  número de bombas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        busqueda.setText("BFS");
        busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaActionPerformed(evt);
            }
        });
        jPanel1.add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setText("Tipo de busqueda:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Selecciona el archivo a cargar y extrae los datos del grafo guardado
     * @param evt 
     */
    private void cargarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarPartidaActionPerformed
        // TODO add your handling code here:
        Csv csv = new Csv();
        Grafo grafo =csv.leerGrafoCSV(csv.seleccionarArchivo("leer"));
        
        this.game=new Juego(grafo,true, metBusqueda);
        this.game.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cargarPartidaActionPerformed
    /**
     * Lee los datos agregados por el usuario y crea el tablero de juego
     * @param evt 
     */
    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        // TODO add your handling code here:
        String columnas = this.numColumnas.getText();
        String filas = this.numFilas.getText();
        String bombas = this.numBombs.getText();
        if (columnas.trim().isEmpty() || filas.trim().isEmpty() || bombas.trim().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Llene las casillas vacias");
        } else{
            int col = Integer.parseInt(columnas);
            int fila=Integer.parseInt(filas);
            int bombs=Integer.parseInt(bombas);
            if (col>=3 && fila>=3 && bombs>=1 && col<=10 && fila<=10 && bombs<col*fila){
                Grafo grafo=new Grafo(fila,col,bombs);
                this.game=new Juego(grafo,false,this.metBusqueda);
                this.game.setVisible(true);
       
      
               
                this.setVisible(false);
            
            } else {
                if (col<3 || fila<3){
                      JOptionPane.showMessageDialog(null, "Las filas y columnas deben ser al menos 3 y debe haber minimo 1 mina");
                } else {
                      JOptionPane.showMessageDialog(null, "Las filas y columnas deben ser maximo 10 y no puede haber mas minas que casillas");
                }
              
            }
    
        } 
        
    }//GEN-LAST:event_botonInicioActionPerformed

    private void numColumnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numColumnasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_numColumnasActionPerformed
/**
 * Es el boton que cambia el metodo de busqueda
 * @param evt 
 */
    private void busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaActionPerformed
        // TODO add your handling code here:
        if (this.metBusqueda){
            this.metBusqueda=false;
            this.busqueda.setText("DFS");
        } else {
            this.metBusqueda=true;
            this.busqueda.setText("BFS");
        }
    }//GEN-LAST:event_busquedaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton busqueda;
    private javax.swing.JButton cargarPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numBombs;
    private javax.swing.JTextField numColumnas;
    private javax.swing.JTextField numFilas;
    // End of variables declaration//GEN-END:variables
}
